stages:
- build
- test
- release

variables:
  TEST_IMAGE: $CI_REGISTRY/$CI_PROJECT_PATH:$CI_COMMIT_REF_NAME       # Working Image during the Pipeline
  RELEASE_IMAGE: $CI_REGISTRY/$CI_PROJECT_PATH:latest                 # Final Image for Release 

# Use Buildah as container builder to avoid using docker:dind
build:
  stage: build
  image: marshallford/podman
  script:
    - podman login -u gitlab-ci-token -p $CI_JOB_TOKEN $CI_REGISTRY
    - podman build --pull -t $TEST_IMAGE .
    - podman push $TEST_IMAGE

test:
  stage: test
  image: marshallford/podman
  #image: docker:18.09.7
  #services:
  #  - docker:18.09.7-dind
  script:
    #- setup_docker
    - podman run -t $TEST_IMAGE

release:
  stage: release
  script:
    - docker pull $TEST_IMAGE
    - docker tag $TEST_IMAGE $RELEASE_IMAGE
    - docker push $RELEASE_IMAGE
  rules:
    - if: $CI_MERGE_REQUEST_IID
      when: never
    - if: '$CI_COMMIT_REF_NAME == "production"'
  environment:
    name: $CI_COMMIT_REF_NAME
    url: https://localhost/

.functions: &functions |
  function setup_docker() {
      if ! docker info &>/dev/null; then
        if [ -z "$DOCKER_HOST" -a "$KUBERNETES_PORT" ]; then
          export DOCKER_HOST='tcp://localhost:2375'
        fi
      fi
    }

before_script:
  - *functions

